### ISSUE TITLE
Zipper support?

### ISSUE THREAD

**Issue by hasufell** [jberryman/directory-tree#10]
So I went with the bifunctor thing from https://github.com/jberryman/directory-tree/issues/7 for now and also noticed that the `AnchoredDirTree` is not suitable for all use cases. One might like to have an actual zipper. So I came up with this module: https://github.com/hasufell/hsfm/blob/master/src/Data/DirTree/Zipper.hs

It is still lazy and also allows to build the parent dirs/breadcrumbs lazily if you drop into a specific directory via [zipLazy](https://github.com/hasufell/hsfm/blob/master/src/Data/DirTree/Zipper.hs#L138), which is sort of the counterpart to `readDirectoryWithL`.

I just throw this out for the discussion. It would be easy to convert it to the current directory-tree API.

**Comment by jberryman** [comment]
Neat! Can you implement it as a new package dependent on `directory-tree`?

**Comment by hasufell** [comment]
I'm not sure I need this any more. I got performance problems with finding things in the `contents` list for huge directories. The lazy representation of the filesystem tree carried too much state around which also became a problem. The strict representation was even moreso problematic when reading stuff like "/",  so I ended up doing things more atomically:

```
data AnchoredDirTree a b =
  (:/) { anchor :: FilePath, dirTree :: IntMap (DirTree a b) }
  deriving (Eq, Ord, Show)

data DirTree a b =
    Failed {
    name :: FileName
  , err  :: IOException
  }
  | Dir {
    name :: FileName
  , dir  :: a
  }
  | File {
    name :: FileName
  , file :: b
  } deriving (Show, Eq)
```
But that's out of the scope of this library. I'm not sure how useful a Zipper actually is.

Representing the filesystem is really difficult since it's an almost random state that can change so quickly that your code-objects that are meant to represent this state may already be out of date.

I don't see a way to keep a _complete_ lazy filesystem tree up to date, do you? As soon as you have looked at a node in the tree, it's static. And if you re-read the filesystem lazily every time you "enter" a subdirectory, then it's a moot point and probably safer to do that explicitly and not depend on the implicit IO through laziness.

**Comment by jberryman** [comment]
You're right, doing lazy IO with a directory tree is inherently weird; it works very nicely for certain applications where you assume the directory isn't changing, and other times it comes with all the usual problems of lazy IO on files, but moreso. Anyway thanks for sharing your experiments. You might see if there are some new solutions on hackage based on streaming libraries that can do what you need. (I'm not really familiar with what's out there these days in this space).

**Comment by hasufell** [comment]
Yeah, I'm having a look at https://hackage.haskell.org/package/conduit-extra-1.1.9.2/docs/Data-Conduit-Filesystem.html which looks interesting. Guess I'll have to learn conduits then :)
