### ISSUE TITLE
Use `unsafeInterleaveIO` instead of `unsafePerformIO`

### ISSUE THREAD

**Issue by Gabriel439** [jberryman/directory-tree#11]
Deep within the code there is this:

```haskell
-- using unsafePerformIO to get "lazy" traversal:
buildLazilyUnsafe' :: Builder a
buildLazilyUnsafe' f p = handleDT n $ 
           do isFile <- doesFileExist p    
              if isFile                         
                 then  File n <$> f p
                  -- HERE IS THE UNSAFE CODE:
                 else Dir n . fmap (rec . combine p) <$> getDirsFiles p
     -- TODO: this should really be unsafeInterleaveIO
     where rec = unsafePerformIO . buildLazilyUnsafe' f
           n = topDir p
```

There is a way to do this using `unsafeInterleaveIO` instead, and I can think of at least one benefit of the switch: `unsafeInterleaveIO` guarantees that the `IO` action it wraps is evaluated at most once (and saved for future references, very much how lazy thunks work in Haskell).  Any action wrapped in `unsafePerformIO` can be run multiple times and give different results if the filesystem changed underneath you in between the two pure evaluations.

This isn't an issue that affects me but somebody brought this my attention at a Hackathon and asked me about the `unsafePerformIO` and `unsafeInterleaveIO` distinction and they also wanted a bug report opened for this, so I wrote one up for them.

**Comment by jberryman** [comment]
Thanks Gabriel. For whatever reason I couldn't get `unsafeInterleaveIO` to work for me initially, but appreciate having the issue open here.
