### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by snoyberg** [jberryman/directory-tree#4]
I'm not sure what's going on in this failure. The test suite works correctly from my machine, but fails from the Stackage Docker image. I'm temporarily disabling the test suite in future Docker builds.

```
Test suite test: RUNNING...
-- The following tests will either fail with an error 
-- message or with an 'undefined' error
OK
OK
OK
OK
test: No match in record selector err
Test suite test: FAIL
```

**Comment by jberryman** [comment]
Thanks. Is it possible that `Test.hs` line 38 is silently failing (i.e. the permissions aren't modified, but no exception is thrown) in the docker environment?

**Comment by snoyberg** [comment]
I discovered the problem: I was running the test suite as `root`, which allows me to read the file even without the read bit set. I *do* need to modify the Docker image to run as a non-root user, I just haven't gotten around to it yet. It's your call whether this is something worth looking into in the test suite.

**Comment by jberryman** [comment]
Ah, that makes sense. Yeah the test suite isn't particularly "robust", but I think I'm leaving it alone for now.
