### ISSUE TITLE
Weird behavior on /dev/fd with readDirectoryWithL

### ISSUE THREAD

**Issue by hasufell** [jberryman/directory-tree#9]
```sh
# ls /dev/fd
0  1  2  3
# file /dev/fd
/dev/fd: symbolic link to /proc/self/fd
# ls /proc/self/fd
0  1  2  3
```
But when reading it via `readDirectoryWithL` I get more files:
```
*System.Directory.Tree> aa <- readDirectoryWithL (\x -> return x) "/dev/fd"
*System.Directory.Tree> aa
(:/) {anchor = "/dev", dirTree = Dir {name = "fd", contents = [
File {name = "0", file = "/dev/fd/0"},
File {name = "1", file = "/dev/fd/1"},File {name = "2", file = "/dev/fd/2"},
File {name = "3", file = "/dev/fd/3"},File {name = "4", file = "/dev/fd/4"},
File {name = "5", file = "/dev/fd/5"},File {name = "6", file = "/dev/fd/6"},
File {name = "7", file = "/dev/fd/7"},File {name = "8", file = "/dev/fd/8"},
File {name = "9", file = "/dev/fd/9"},File {name = "10", file = "/dev/fd/10"}]}}
```

Surely those directories are special and it seems laziness causes weird behavior here. Do these directories change frequently or what is the thing here?

**Comment by hasufell** [comment]
Aha... `/proc/self` is a symlink to something like `/proc/<num>`, where `<num>` seems to change frequently... inside that directory there exists indeed those mentioned files. I wonder why `ls` doesn't show these at all?

**Comment by jberryman** [comment]
I'm afraid I don't really know how those magical unix file thingies like proc work, but I see how there is some strangeness happening. E.g.

    jberryman dev/system-tests ‹brandons-fixups*› » ls /proc/self/fd 
    0  1  2  3

vs the output I get from zsh tab completion:

    jberryman dev/system-tests ‹brandons-fixups*› » ls /proc/self/fd/
    0@   1@   10@  11@  12@  13   2@   3

**Comment by hasufell** [comment]
I guess we could say then this is a general problem. I only stumbled over this because it caused a runtime exception at some point if the call order in `buildLazilyUnsafe'` wasn't done carefully.

**Comment by jberryman** [comment]
what was the exception?

**Comment by hasufell** [comment]
```
Exception: /dev/fd/11: getDirectoryContents: does not exist (No such file or directory)
```
As soon as I move the `files <- getDirsFiles p` out of `unsafeInterleaveIO`, then it's fine and the error does not occur. It seems reading the directory contents must be a little less lazy.
